# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publish Build Artifacts
# Publish build artifacts to Azure Pipelines/TFS or a file share

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise (6064f5b1-01a1-4bdb-b038-fcbe2d3a7d65)'
    appType: 'webAppLinux'
    WebAppName: 'Flatrix-May-2020'
    packageForLinux: '$(System.DefaultWorkingDirectory)/*.zip'



